security:
    # Gestion du hashage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Chargement des utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UserAuthenticator
            logout:
                path: app_logout
                target: app_front_accueil_accueil # Redirection après déconnexion

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    # Contrôle d'accès basé sur les rôles
    access_control:
        - { path: ^/back/bien, roles: ROLE_ADMIN }             # Accès uniquement pour ADMIN
        - { path: ^/back/dashboard, roles: ROLE_ADMIN }        # Accès uniquement pour ADMIN
        - { path: ^/back/details_propriete, roles: ROLE_ADMIN } # Accès uniquement pour ADMIN
        - { path: ^/propriete, roles: ROLE_ADMIN }             # Accès uniquement pour ADMIN
        - { path: ^/back/type/bien, roles: ROLE_ADMIN }        # Accès uniquement pour ADMIN
        - { path: ^/back/user, roles: ROLE_ADMIN }             # Accès uniquement pour ADMIN
        - { path: ^/admin, roles: ROLE_ADMIN }                 # Accès uniquement pour ADMIN

        



when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
